version: '3.3'

services:
  auntbertha-backend:
    container_name: auntbertha-backend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './backend:/app'
    ports:
      - 4000:4000
      - 5001:5000
    environment:
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@db:5432/zipcode_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@db:5432/zipcode_test
    depends_on:
      - db
    links:
      - db

  db:
    container_name: db
    build:
      context: ./backend/project/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres